### ISSUE TITLE
can u please add the .ui file 

### ISSUE THREAD

**Issue by ahmadkarimi4** [diegosticks/Python_GUI_Email_Sender#1]
hi this is very helpful but i need to make some changes so if u have please add .UI file of this design

**Comment by diegosticks** [comment]
I uploaded it straight from pycharm where I wrote the code. I did it with PYQT. You need to have that installed. Clone and run the program. Yo can choose to convert it to an executable file too.

**Comment by ahmadkarimi4** [comment]
i know all that but u didnt use QT designer for this ?

**Comment by diegosticks** [comment]
Please read the read me file on github and get your information.
    On Wednesday, November 30, 2022 at 07:24:23 AM GMT+1, ahmadkarimi4 ***@***.***> wrote:  
 
 


i know all that but u didnt use QT designer for this ?
